MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "../MMA222/output/10-10/pse_ini_l4h75_psew93/STEP1/model_0012000.pth"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    USE_FPN: False
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    EXTERNAL_PROPOSAL: False
  ROI_HEADS:
    USE_FPN: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 0
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    NUM_CLASSES: 11 # total classes : 15 + 1
    NAME_OLD_CLASSES: []
    NAME_NEW_CLASSES: ["diningtable", "dog","horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]
    NAME_EXCLUDED_CLASSES: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow"]
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  # TEST: ("voc_2007_test",)
  TEST: ("voc_2007_trainval",)
DATALOADER:
  SIZE_DIVISIBILITY: 0
SOLVER:
  BASE_LR: 0.001 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (7500,)
  MAX_ITER: 10000 #10000 # number of iteration
  CHECKPOINT_PERIOD: 2000 # number of iteration to generate check point
  IMS_PER_BATCH: 2 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 2 # number of images per batch
OUTPUT_DIR: "results/" # path to store the result
TENSORBOARD_DIR: "results/" # path to store tensorboard info
