MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/ageraci/FILOD/results/instance_seg/source_models/10_10/model_final.pth"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 11
    NAME_OLD_CLASSES: [ "aeroplane", "bicycle", "bird","boat", "bottle", "bus", "car", "cat", "chair", "cow"]
    NAME_NEW_CLASSES: [ "diningtable", "dog",
                        "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor" ]
    NAME_EXCLUDED_CLASSES: []
  MASK_ON: True
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True
DATASETS:
  TRAIN: ("voc_2012_train",)
  TEST: ("voc_2012_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 0
SOLVER:
  BASE_LR: 0.0005 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (20000,25000)
  MAX_ITER: 30000 # number of iteration
  CHECKPOINT_PERIOD: 5000 # number of iteration to generate check point
  IMS_PER_BATCH: 4 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 1 # number of images per batch
OUTPUT_DIR: "/home/ageraci/FILOD/results/files/useless" # path to store the result
TENSORBOARD_DIR: "/home/ageraci/FILOD/results/useless/tensorboard" # path to store tensorboard info
INCREMENTAL: False